In [2]:
!pip install -U yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.11/dist-packages (0.2.52)
Collecting yfinance
  Downloading yfinance-0.2.53-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2025.1)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.11/dist-packages (from yfinance) (3.17.9)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.13.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Downloading yfinance-0.2.53-py2.py3-none-any.whl (108 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.5/108.5 kB 3.4 MB/s eta 0:00:00
Installing collected packages: yfinance
  Attempting uninstall: yfinance
    Found existing installation: yfinance 0.2.52
    Uninstalling yfinance-0.2.52:
      Successfully uninstalled yfinance-0.2.52
Successfully installed yfinance-0.2.53

In [30]:
import yfinance as yf
import pandas as pd
import numpy as np


# Net Income (순이익) 추출 함수
def get_net_income_from_operatings(stock, q_data=True):
  if q_data:
    financials = stock.quarterly_financials.T
  else:
    financials = stock.financials.T
  return financials["Net Income Continuous Operations"]

# Operating Cash Flow (영업활동 현금흐름) 추출 함수
def get_operating_cashflow(stock, q_data=True):
  if q_data:
    cashflow = stock.quarterly_cashflow.T
  else:
    cashflow = stock.cashflow.T
  return cashflow["Cash Flow From Continuing Operating Activities"]

def get_total_asset(stock, q_data=True):
  if q_data:
    balancesheet = stock.quarterly_balancesheet.T
  else:
    balancesheet = stock.balancesheet.T
  return balancesheet['Total Assets']

def get_net_income(stock, q_data=True):
  if q_data:
    financials = stock.quarterly_financials.T
  else:
    financials = stock.financials.T
  return financials['Net Income']

# Cash Dividends Paid (배당금 지급) 추출 함수
def get_cash_dividends_paid(stock, q_data=True):
  if q_data:
    cashflow = stock.quarterly_cashflow.T
  else:
    cashflow = stock.cashflow.T
  return cashflow["Cash Dividends Paid"]

# Repurchase of Capital Stock (자사주 매입) 추출 함수
def get_repurchase_of_stock(stock, q_data=True):
  if q_data:
    cashflow = stock.quarterly_cashflow.T
  else:
    cashflow = stock.cashflow.T
  return cashflow["Repurchase Of Capital Stock"]


# 모든 데이터를 종합하는 함수
def get_financial_data(ticke, q_date=True):
    stock = yf.Ticker(ticker)

    # 개별 함수 호출하여 데이터 추출
    net_income = get_net_income(stock, q_date)
    cash_dividends_paid = get_cash_dividends_paid(stock, q_date)
    repurchase_of_stock = get_repurchase_of_stock(stock, q_date)
    net_income_from_operatings = get_net_income_from_operatings(stock, q_date)
    cashflow_of_operating = get_operating_cashflow(stock, q_date)
    total_asset = get_total_asset(stock, q_date)

    # 데이터프레임 생성
    df = pd.DataFrame({
        'Net Income': net_income,
        'Cash Dividends Paid': cash_dividends_paid,
        'Repurchase of Capital Stock': repurchase_of_stock,
        'Net Income from Operating':net_income_from_operatings,
        'Cashflow of Operating':cashflow_of_operating,
        'Shareholder Return': cash_dividends_paid + repurchase_of_stock,
        '영업 활동으로 발생하는 현금 흐름 (Income/Operating) %': (net_income_from_operatings/cashflow_of_operating)*100,
        '자산 대비 수익 창출 능력 (Income/Assets) %': (net_income_from_operatings/total_asset)*100
    })
    df.index = df.index.strftime('%y') + "Q" + df.index.to_period("Q").astype(str).str[-1]
    return df

In [33]:
# 예시 종목: 애플 (AAPL)
ticker = "NKE"
df = get_financial_data(ticker)

In [34]:
df['영업 활동으로 발생하는 현금 흐름 (Income/Operating) %'].sort_index()

23Q2           NaN
23Q3           NaN
23Q4     56.017039
24Q1     56.920835
24Q2     57.273769
24Q3    266.751269
24Q4    110.867493
Name: 영업 활동으로 발생하는 현금 흐름 (Income/Operating) %, dtype: object

In [35]:
df['자산 대비 수익 창출 능력 (Income/Assets) %'].sort_index()

23Q2         NaN
23Q3         NaN
23Q4    4.241593
24Q1    3.137381
24Q2    3.935975
24Q3    2.775504
24Q4    3.063832
Name: 자산 대비 수익 창출 능력 (Income/Assets) %, dtype: object

In [36]:
df/np.power(10,9)

,Net Income,Cash Dividends Paid,Repurchase of Capital Stock,Net Income from Operating,Cashflow of Operating,Shareholder Return,영업 활동으로 발생하는 현금 흐름 (Income/Operating) %,자산 대비 수익 창출 능력 (Income/Assets) %
24Q4,1.163,-0.557,-1.096,1.163,1.049,-1.653,0.0,0.0
24Q3,1.051,-0.558,-1.184,1.051,0.394,-1.742,0.0,0.0
24Q2,1.5,-0.56,-1.036,1.5,2.619,-1.596,0.0,0.0
24Q1,1.172,-0.562,-0.883,1.172,2.059,-1.445,0.0,0.0
23Q4,1.578,-0.523,-1.198,1.578,2.817,-1.721,0.0,0.0
23Q3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN