In [1]:
!pip install -U yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.11/dist-packages (0.2.52)
Collecting yfinance
  Downloading yfinance-0.2.54-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2025.1)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.11/dist-packages (from yfinance) (3.17.9)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.13.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Downloading yfinance-0.2.54-py2.py3-none-any.whl (108 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.7/108.7 kB 2.6 MB/s eta 0:00:00
Installing collected packages: yfinance
  Attempting uninstall: yfinance
    Found existing installation: yfinance 0.2.52
    Uninstalling yfinance-0.2.52:
      Successfully uninstalled yfinance-0.2.52
Successfully installed yfinance-0.2.54

In [8]:
import yfinance as yf
import pandas as pd
import numpy as np


# Net Income (순이익) 추출 함수
def get_net_income_from_operatings(stock, q_data=True):
  if q_data:
    financials = stock.quarterly_financials.T
  else:
    financials = stock.financials.T
  return financials["Net Income Continuous Operations"]

# Operating Cash Flow (영업활동 현금흐름) 추출 함수
def get_operating_cashflow(stock, q_data=True):
  if q_data:
    cashflow = stock.quarterly_cashflow.T
  else:
    cashflow = stock.cashflow.T
  return cashflow["Cash Flow From Continuing Operating Activities"]

def get_total_asset(stock, q_data=True):
  if q_data:
    balancesheet = stock.quarterly_balancesheet.T
  else:
    balancesheet = stock.balancesheet.T
  return balancesheet['Total Assets']

def get_net_income(stock, q_data=True):
  if q_data:
    financials = stock.quarterly_financials.T
  else:
    financials = stock.financials.T
  return financials['Net Income']

# Cash Dividends Paid (배당금 지급) 추출 함수
def get_cash_dividends_paid(stock, q_data=True):
  if q_data:
    cashflow = stock.quarterly_cashflow.T
  else:
    cashflow = stock.cashflow.T
  return cashflow["Cash Dividends Paid"]

# Repurchase of Capital Stock (자사주 매입) 추출 함수
def get_repurchase_of_stock(stock, q_data=True):
  if q_data:
    cashflow = stock.quarterly_cashflow.T
  else:
    cashflow = stock.cashflow.T
  return cashflow["Repurchase Of Capital Stock"]


# 모든 데이터를 종합하는 함수
def get_financial_data(ticke, q_date=True):
    stock = yf.Ticker(ticker)

    # 개별 함수 호출하여 데이터 추출
    net_income = get_net_income(stock, q_date)
    cash_dividends_paid = get_cash_dividends_paid(stock, q_date)
    repurchase_of_stock = get_repurchase_of_stock(stock, q_date)
    net_income_from_operatings = get_net_income_from_operatings(stock, q_date)
    cashflow_of_operating = get_operating_cashflow(stock, q_date)
    total_asset = get_total_asset(stock, q_date)

    # 데이터프레임 생성
    df = pd.DataFrame({
        'Net Income': net_income,
        'Cash Dividends Paid': cash_dividends_paid,
        'Repurchase of Capital Stock': repurchase_of_stock,
        'Net Income from Operating':net_income_from_operatings,
        'Cashflow of Operating':cashflow_of_operating,
        'Shareholder Return': cash_dividends_paid + repurchase_of_stock,
        '영업 활동으로 발생하는 현금 흐름 (Income/Operating) %': (net_income_from_operatings/cashflow_of_operating)*100,
        '자산 대비 수익 창출 능력 (Income/Assets) %': (net_income_from_operatings/total_asset)*100
    })
    df.index = df.index.strftime('%y') + "Q" + df.index.to_period("Q").astype(str).str[-1]
    return df

In [9]:
# 예시 종목: 애플 (AAPL)
ticker = "SBUX"
df = get_financial_data(ticker)

In [13]:
df['영업 활동으로 발생하는 현금 흐름 (Income/Operating) %'].round(1).sort_index()

23Q2           NaN
23Q3           NaN
23Q4     42.971601
24Q1    152.667984
24Q2     63.211784
24Q3     59.234176
24Q4     37.688224
Name: 영업 활동으로 발생하는 현금 흐름 (Income/Operating) %, dtype: object

In [5]:
df['자산 대비 수익 창출 능력 (Income/Assets) %'].sort_index()

23Q2         NaN
23Q3         NaN
23Q4     3.51066
24Q1    2.630844
24Q2    3.505935
24Q3    2.902426
24Q4    2.448492
Name: 자산 대비 수익 창출 능력 (Income/Assets) %, dtype: object

In [6]:
df.sort_index()/np.power(10,9)

,Net Income,Cash Dividends Paid,Repurchase of Capital Stock,Net Income from Operating,Cashflow of Operating,Shareholder Return,영업 활동으로 발생하는 현금 흐름 (Income/Operating) %,자산 대비 수익 창출 능력 (Income/Assets) %
23Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23Q3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23Q4,1.0244,-0.6481,-1.2667,1.0244,2.3839,-1.9148,0.0,0.0
24Q1,0.7724,-0.6454,0.0,0.7725,0.506,-0.6454,0.0,0.0
24Q2,1.0548,-0.6455,0.0,1.0557,1.6701,-0.6455,0.0,0.0
24Q3,0.9092,-0.646,0.0,0.9096,1.5356,-0.646,0.0,0.0
24Q4,0.7808,-0.6919,0.0,0.7809,2.072,-0.6919,0.0,0.0

In [7]:
stock = yf.Ticker(ticker)

In [1]:
weekly_data = stock.history(period="1y", interval="1wk")  # 1년 동안의 주간 데이터
weekly_close = weekly_data['Close']
weekly_close

NameError: name 'stock' is not defined

In [4]:
import yfinance as yf
import pandas as pd

# 커피 선물(KC=F) 데이터 다운로드 (1년치, 월간 데이터)
coffee = yf.Ticker("KC=F")
monthly_data = coffee.history(period="1y", interval="1wk")["Close"]

# 인덱스를 월로 포맷팅하고 값은 정수로 변환
monthly_data.index = monthly_data.index.to_period('M')
monthly_data = monthly_data.astype(int)

# print(monthly_data)

<ipython-input-4-66ad02951b10>:9: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  monthly_data.index = monthly_data.index.to_period('M')

In [6]:
import pandas as pd
import numpy as np


def get_beta_corr(ticker="MSFT"):

  compare_cols_dict = {
                                '^GSPC': 'S&P 500',
                                '^DJI': 'DJI',
                                '^IXIC': 'NASDAQ',
                                '^STOXX50E': 'EURO STOXX 50',
                                '^HSI': 'HANG SENG',
                                '^KS11': 'KOSPI',
                                '^N225': 'Nikkei',
                                'GC=F': 'Gold',
                                'ZN=F': '10-Year T-Note',
                                'ZT=F': '2-Year T-Note',
                                'HG=F': 'Copper',
                                'CL=F': 'Crude Oil',
                                'NG=F': 'Natural Gas',
                                'KC=F': 'Coffee',
                                'CC=F': 'Cocoa',
                                'SB=F': 'Sugar'
                            }
  compare_cols = list(compare_cols_dict.keys())
  compare_cols.append(ticker)
  compare_cols.reverse()
  df = list()
  for col in compare_cols:
    close_price= yf.download(col, period='1mo')['Close']
    df.append(close_price)
  df=pd.concat(df, axis=1)
  df = df.ffill()
  df = df.pct_change()
  df = df.dropna()
  # return df

  base_col = ticker
  compare_cols.remove(base_col)

  # 베타 및 상관계수 저장용 딕셔너리
  results = {}

  for col in compare_cols:
      # 공분산 계산
      covariance = np.cov(df[base_col], df[col])[0, 1]
      # 비교군 분산 계산
      variance = np.var(df[col], ddof=1)  # np.var 기본 ddof=0, 샘플 분산은 ddof=1
      # 베타 값 계산
      beta = covariance / variance
      # 상관계수 계산
      correlation = np.corrcoef(df[base_col], df[col])[0, 1]
      results[col] = {"Beta": beta, "Correlation": correlation}

  results_df = pd.DataFrame(results)
  results_df = results_df.rename(columns=compare_cols_dict)
  results_df= results_df.T
  results_df = results_df.round(1)
  return results_df

In [7]:
get_beta_corr('SBUX')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

                Beta  Correlation
Sugar            0.1          0.1
Cocoa            0.2          0.3
Coffee           0.2          0.2
Natural Gas     -0.0         -0.1
Crude Oil       -0.7         -0.5
Copper           0.3          0.2
2-Year T-Note   -1.4         -0.1
10-Year T-Note   0.2          0.0
Gold            -0.0         -0.0
Nikkei           0.4          0.2
KOSPI           -0.0         -0.0
HANG SENG        0.1          0.1
EURO STOXX 50    0.2          0.1
NASDAQ          -0.3         -0.2
DJI             -0.3         -0.1
S&P 500         -0.6         -0.2

In [ ]:
close_price= yf.download(col, period='1mo')['Close']